# Generated by Django 6.0 on 2025-12-13 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_nickname_userprofile_nickname_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicknameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname_history', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['nickname'], name='accounts_ni_nicknam_bd65b3_idx')],
            },
        ),
    ]
