# Generated by Django 6.0 on 2025-12-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room'), ('maisonette', 'Maisonette'), ('penthouse', 'Penthouse'), ('office', 'Office'), ('retail', 'Retail'), ('warehouse', 'Warehouse'), ('parking', 'Parking'), ('land', 'Land')], max_length=32)),
                ('rooms', models.DecimalField(decimal_places=1, help_text='Например 2.5 — типично для DE', max_digits=3)),
                ('area_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.SmallIntegerField(blank=True, help_text='Этаж квартиры', null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, help_text='Этажность здания', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.location')),
            ],
        ),
    ]
