# Generated by Django 6.0 on 2026-01-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_amenity_property_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.SmallIntegerField(blank=True, help_text='Apartment floor', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of floors of the building', null=True),
        ),
    ]
