# Generated by Django 6.0 on 2026-01-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country'], name='locations_l_country_7a39b7_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['state'], name='locations_l_state_93f5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city'], name='locations_l_city_05dac7_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['postal_code'], name='locations_l_postal__01f758_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['state', 'city'], name='locations_l_state_51ae7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('country', 'state', 'city', 'postal_code'), name='unique_location_city_zip'),
        ),
    ]
