# Generated by Django 6.0 on 2025-12-15 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_nicknamehistory'),
        ('bookings', '0005_alter_booking_options'),
        ('reviews', '0002_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='direction',
            field=models.CharField(choices=[('tenant_to_landlord', 'Tenant → Landlord'), ('landlord_to_tenant', 'Landlord → Tenant')], default='tenant_to_landlord', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('booking', 'direction'), name='unique_review_per_booking_direction'),
        ),
    ]
