# Generated by Django 6.0 on 2025-12-16 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_nicknamehistory'),
        ('bookings', '0005_alter_booking_options'),
        ('reviews', '0005_userrating_delete_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='property_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.propertyrating'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'tenant_to_landlord'), ('property_rating__isnull', False)), models.Q(('direction', 'landlord_to_tenant'), ('property_rating__isnull', True)), _connector='OR'), name='property_rating_only_for_tenant_reviews'),
        ),
    ]
