# Generated by Django 6.0 on 2025-12-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_property_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('user_removed', 'Removed by user'), ('moderator_removed', 'Removed by moderator')], default='approved', max_length=20),
        ),
    ]
