# Generated by Django 6.0 on 2025-12-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Optional text review'),
        ),
    ]
