# Generated by Django 6.0 on 2025-12-19 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_review_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('user_removed', 'Removed by user'), ('moderator_removed', 'Removed by moderator'), ('moderator_restored', 'Moderator restored'), ('moderator_hidden', 'Moderator hidden'), ('moderator_unhidden', 'Moderator unhidden')], max_length=32)),
                ('from_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('user_removed', 'Removed by user'), ('moderator_removed', 'Removed by moderator')], max_length=32, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('user_removed', 'Removed by user'), ('moderator_removed', 'Removed by moderator')], max_length=32, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='reviews.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
