# Generated by Django 6.0 on 2026-01-02 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_reviewaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='property_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.propertyrating'),
        ),
    ]
